backend:
  name: git-gateway
  branch: main

  publish_mode: editorial_workflow

media_library:
  name: cloudinary
  config:
    cloud_name: dxqnpsj8k
    api_key: 145836922335926
    upload_preset: netlify_cms

media_folder: ""
public_folder: ""

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blogs"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - label: "Featured Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: true

      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "destinations"
    label: "Destinations"
    folder: "src/destinations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Hero Image",
          name: "hero_image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
